### ISSUE TITLE
feat: code snippet tester

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#139]
To make the maintenance process easier, I would like to integrate in the CI a tool that extracts all compilable code snippets and compiles them. This will ensure that code snippets are executable and make it easier to spot breaking changes due to version updates. 

We could annotate "fenced" code blocks with a `does_not_compile` attribute to indicate code snippets that can't be compiled, like chunks of programs or isolated functions. 

@glihm suggested to adapt [this program ](https://github.com/google/comprehensive-rust/tree/main/mdbook-exerciser) for our needs

**Comment by enitrat** [comment]
Would love to :pray:

**Comment by glihm** [comment]
@enitrat and others, I would like to have your opinion on this:

We use fenced code block for cairo examples. Which is nice. Here is my suggestion to hide the implementation details to the reader:

1. Instead of having a filename formatted in HTML or other before the code block, we can add attributes to the tag. The tag is not visible after rendering.
2. The tag can have several attributes, and the syntax color of the code is only determined by the first attribute.
3. Like this, we can then only specify a filename for the fence code block when we want mdbook to generate a cairo program.


````
```rust,file=hello_world.cairo
use debug::PrintTrait;
fn main() {
    'Hello, world!'.print();
}                                                                                                                                        
```
````

Like this, the syntax is preserved, and the parser will know it has to generate a file named `hello_worl.cairo`.

````
```rust
    'Hello, world!'.print();                                                                                                                                    
```
````

Like this, we just want to explain part of the code, no file will be generated.

Sounds good for you guys? Or do you prefer relying on a special syntax, like the filename, that is always preceding the code block?

**Comment by enitrat** [comment]
Sounds good
