### ISSUE TITLE
Solidity to Cairo migration

### ISSUE THREAD

**Issue by ashutosh887** [cairo-book/cairo-book.github.io#341]
- I believe there should be a section in the Cairo Book to help smart contract developers migrate their Solidity Contracts/Code to Cairo Contracts, basically to compare different languages based on the features they offer and in any ways, if they correlate.

**Comment by ashutosh887** [comment]
And yeah sure, I would like to work on this

**Comment by enitrat** [comment]
Hey @ashutosh887 thanks for the idea!

I don't think it's suitable for the Cairo book - it could be for an external resource. While the overall idea is good, we don't want to spread ourselves too thin in the book - and I would rather not have Solidity code in a Cairo-centric that is not aimed at Solidity developers.
Rather than directly comparing Solidity and Cairo at the code level, I chose to have approach things at the conceptual level - that's what the book has now with specific sections on Storage, Events, function visibility, etc.

The architecture and organization of a Solidity contract should not be 1:1 mirrored to a Cairo contract, as both languages have design differences.

**Comment by enitrat** [comment]
However if you believe that migrating a Solidity contract to Cairo is not easy because it's not clear how some high-level concepts can be translated I'm totally open to adding a new section on whatever is missing
