### ISSUE TITLE
Add a section about `ExecutionInfo`

### ISSUE THREAD

**Issue by glihm** [cairo-book/cairo-book.github.io#406]
This seems trivial, but actually more people than I expected are questioning about basic information like block timestamp, transaction hash etc...

It could be great to add a little piece of information about them and how to use them.
The list of functions can be found here: https://github.com/starkware-libs/cairo/blob/0f0b3786e7dfdbbff681cfbb78a9dd181f2c4608/corelib/src/starknet/info.cairo#L46

@enitrat sounds good for a good first issue too, right?

**Comment by enitrat** [comment]
yes and no at the same time - It's always a bit hard to know what should be in scope of the book and what shouldn't be. For that matter I think this should be part of an eventual documentation of the standard library, or starknet docs, but since it doesn't exist, well, maybe we should do it ourselves

**Comment by glihm** [comment]
Hum.. you're right, maybe not in the book's scope.
even if I think well, it can be good to have this somewhere even in appendices what do you think?

If you think we should include it, I can give it a shot.

**Comment by enitrat** [comment]
Is this page not enough? https://docs.starknet.io/documentation/architecture_and_concepts/Smart_Contracts/system-calls-cairo1/#get_execution_info

Should we modify this page directly instead/ WDYT?

**Comment by glihm** [comment]
Sounds good! Thank you for the feedback @enitrat. 🫡
